PATHS = [
    # '/author',
    # '/author/lookup',
    # '/system/backup',
    # '/blacklist',
    # '/book',
    # '/bookfile',
    # '/book/lookup',
    # '/calendar',
    # '/calendar/readarr.ics',
    # '/command',
    '/customfilter',
    # '/wanted/cutoff',
    '/delayprofile',
    # '/config/development',
    # '/diskspace',
    '/downloadclient',
    # '/downloadclient/schema',
    '/config/downloadclient',
    # '/filesystem',
    # '/filesystem/type',
    # '/filesystem/mediafiles',
    # '/health',
    # '/history',
    # '/history/since',
    # '/history/author',
    '/config/host',
    # '/importlist',
    # '/importlist/schema',
    # '/importlistexclusion',
    '/indexer',
    # '/indexer/schema',
    '/config/indexer',
    # '/language',
    # '/localization',
    # '/log',
    # '/log/file',
    # '/manualimport',
    '/config/mediamanagement',
    '/metadata',
    # '/metadata/schema',
    '/metadataprofile',
    # '/metadataprofile/schema',
    '/config/metadataprovider',
    # '/wanted/missing',
    '/config/naming',
    # '/config/naming/examples',
    '/notification',
    # '/notification/schema',
    # '/parse',
    '/qualitydefinition',
    '/qualityprofile',
    # '/qualityprofile/schema',
    # '/queue',
    # '/queue/details',
    # '/queue/status',
    # '/release',
    '/releaseprofile',
    '/remotepathmapping',
    # '/rename',
    # '/retag',
    '/rootfolder',
    # '/search',
    # '/series',
    # '/system/status',
    # '/system/routes',
    # '/system/routes/duplicate',
    '/tag',
    # '/tag/detail',
    # '/system/task',
    '/config/ui',
    # '/update',
    # '/log/file/update'
]
