PATHS = [
    # '/api/v1/author',
    # '/api/v1/author/lookup',
    # '/api/v1/system/backup',
    # '/api/v1/blacklist',
    # '/api/v1/book',
    # '/api/v1/bookfile',
    # '/api/v1/book/lookup',
    # '/api/v1/calendar',
    # '/api/v1/calendar/readarr.ics',
    # '/api/v1/command',
    '/api/v1/customfilter',
    # '/api/v1/wanted/cutoff',
    '/api/v1/delayprofile',
    # '/api/v1/config/development',
    # '/api/v1/diskspace',
    '/api/v1/downloadclient',
    # '/api/v1/downloadclient/schema',
    '/api/v1/config/downloadclient',
    # '/api/v1/filesystem',
    # '/api/v1/filesystem/type',
    # '/api/v1/filesystem/mediafiles',
    # '/api/v1/health',
    # '/api/v1/history',
    # '/api/v1/history/since',
    # '/api/v1/history/author',
    '/api/v1/config/host',
    # '/api/v1/importlist',
    # '/api/v1/importlist/schema',
    # '/api/v1/importlistexclusion',
    '/api/v1/indexer',
    # '/api/v1/indexer/schema',
    '/api/v1/config/indexer',
    # '/api/v1/language',
    # '/api/v1/localization',
    # '/api/v1/log',
    # '/api/v1/log/file',
    # '/api/v1/manualimport',
    '/api/v1/config/mediamanagement',
    '/api/v1/metadata',
    # '/api/v1/metadata/schema',
    '/api/v1/metadataprofile',
    # '/api/v1/metadataprofile/schema',
    '/api/v1/config/metadataprovider',
    # '/api/v1/wanted/missing',
    '/api/v1/config/naming',
    # '/api/v1/config/naming/examples',
    '/api/v1/notification',
    # '/api/v1/notification/schema',
    # '/api/v1/parse',
    '/api/v1/qualitydefinition',
    '/api/v1/qualityprofile',
    # '/api/v1/qualityprofile/schema',
    # '/api/v1/queue',
    # '/api/v1/queue/details',
    # '/api/v1/queue/status',
    # '/api/v1/release',
    '/api/v1/releaseprofile',
    '/api/v1/remotepathmapping',
    # '/api/v1/rename',
    # '/api/v1/retag',
    '/api/v1/rootfolder',
    # '/api/v1/search',
    # '/api/v1/series',
    # '/api/v1/system/status',
    # '/api/v1/system/routes',
    # '/api/v1/system/routes/duplicate',
    '/api/v1/tag',
    # '/api/v1/tag/detail',
    # '/api/v1/system/task',
    '/api/v1/config/ui',
    # '/api/v1/update',
    # '/api/v1/log/file/update'
]
