PATHS = {
    'lidarr': [
        # '/album',
        # '/album/lookup',
        # '/artist',
        # '/artist/lookup',
        '/customfilter',
        '/delayprofile',
        '/downloadclient',
        '/config/downloadclient',
        # '/filesystem',
        # '/filesystem/type',
        # '/filesystem/mediafiles',
        '/config/host',
        '/importlist',
        '/importlistexclusion',
        '/indexer',
        '/config/indexer',
        # '/language',
        # '/localization',
        # '/manualimport',
        '/config/mediamanagement',
        '/metadata',
        '/metadataprofile',
        '/config/metadataprovider',
        '/config/naming',
        # '/config/naming/examples',
        '/notification',
        '/qualitydefinition',
        '/qualityprofile',
        '/releaseprofile',
        '/remotepathmapping',
        '/rootfolder',
        '/tag',
        '/tag/detail',
        # '/system/task',
        '/track',
        '/trackfile',
        '/config/ui',
    ],
    'prowlarr': [
        '/applications',
        '/appprofile',
        '/customfilter',
        '/config/development',
        '/downloadclient',
        '/config/downloadclient',
        # '/filesystem',
        # '/filesystem/type',
        '/config/host',
        '/indexer',
        '/indexer/categories',
        '/indexerproxy',
        # '/indexerstats',
        '/indexerstatus',
        # '/localization',
        # '/localization/options',
        '/notification',
        '/system/status',
        '/tag',
        '/tag/detail',
        '/system/task',
        '/config/ui',
    ],
    'radarr': [
        # '/alttitle',
        # '/collection',
        # '/credit',
        '/customfilter',
        '/customformat',
        '/delayprofile',
        '/downloadclient',
        '/config/downloadclient',
        # '/extrafile',
        # '/filesystem',
        # '/filesystem/type',
        # '/filesystem/mediafiles',
        '/config/host',
        '/exclusions',
        # '/importlist',
        '/config/importlist',
        # '/importlist/movie',
        '/indexer',
        '/config/indexer',
        '/indexerflag',
        # '/language',
        # '/localization',
        # '/manualimport',
        '/config/mediamanagement',
        '/metadata',
        '/config/metadata',
        # '/movie',
        # '/moviefile',
        # '/movie/lookup/tmdb',
        # '/movie/lookup/imdb',
        # '/movie/lookup',
        '/config/naming',
        # '/config/naming/examples',
        '/notification',
        '/qualitydefinition',
        '/qualityprofile',
        '/remotepathmapping',
        '/restriction',
        '/rootfolder',
        # '/system/status',
        '/tag',
        '/tag/detail',
        # '/system/task',
        '/config/ui',
    ],
    'readarr': [
        # '/author',
        # '/author/lookup',
        # '/blacklist',
        # '/book',
        # '/bookfile',
        # '/book/lookup',
        '/customfilter',
        '/delayprofile',
        # '/config/development',
        '/downloadclient',
        # '/downloadclient/schema',
        '/config/downloadclient',
        # '/filesystem',
        # '/filesystem/type',
        # '/filesystem/mediafiles',
        '/config/host',
        # '/importlist',
        # '/importlist/schema',
        # '/importlistexclusion',
        '/indexer',
        # '/indexer/schema',
        '/config/indexer',
        # '/language',
        # '/localization',
        # '/manualimport',
        '/config/mediamanagement',
        '/metadata',
        # '/metadata/schema',
        '/metadataprofile',
        # '/metadataprofile/schema',
        '/config/metadataprovider',
        '/config/naming',
        # '/config/naming/examples',
        '/notification',
        # '/notification/schema',
        '/qualitydefinition',
        '/qualityprofile',
        # '/qualityprofile/schema',
        '/releaseprofile',
        '/remotepathmapping',
        '/rootfolder',
        # '/series',
        # '/system/status',
        # '/system/routes',
        # '/system/routes/duplicate',
        '/tag',
        # '/tag/detail',
        # '/system/task',
        '/config/ui',
    ],
    'sonarr': [
        '/customfilter',
        '/customformat',
        '/delayprofile',
        '/downloadclient',
        '/config/downloadclient',
        # '/episode',
        # '/episodefile',
        # '/filesystem',
        # '/filesystem/type',
        # '/filesystem/mediafiles',
        '/config/host',
        '/importlist',
        '/importlistexclusion',
        '/indexer',
        '/config/indexer',
        # '/languageprofile',
        # '/manualimport',
        '/config/mediamanagement',
        '/metadata',
        '/config/naming',
        # '/config/naming/examples',
        '/notification',
        '/qualitydefinition',
        '/qualityprofile',
        '/releaseprofile',
        '/remotepathmapping',
        '/rootfolder',
        # '/series',
        # '/series/lookup',
        # '/system/status',
        '/tag',
        '/tag/detail',
        # '/system/task',
        '/config/ui'
    ]
}
