name: docker
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME || github.actor }}
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN || github.token }}
      DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME == '' && 'ghcr.io' || 'docker.io'  }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Output Docker Repo
        run: |
          if [[ "${{ github.actor }}" == "$DOCKER_USERNAME" ]]; then
            echo "DOCKER_REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
          else
            echo "DOCKER_REPO=${DOCKER_USERNAME}/flemmarr" >> "${GITHUB_ENV}"
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:latest
